elasticsearch:
  image: elasticsearch
  command: elasticsearch
  ports:
   - "9200:9200"
   - "9300:9300"

logstash:
  image: logstash
  hostname: "logstash"
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
   - ./logstash/config:/etc/logstash/conf.d
  ports:
   - "5000:5000"
  links:
   - elasticsearch


kibana:
  image: kibana
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
   - "5601:5601"
  links:
   - elasticsearch 